[build-system]
requires = [
    "setuptools",
    "setuptools_scm"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120

[tool.pipy]
name = "pipy"

[[tool.pipy.aliases]]
name = "setup"
commands = [
    "pip install --upgrade pip"
]
